name: Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  deploy-staging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'https://signifly.dev'
    steps:
      - name: Deploy
        run: echo I am deploying!

  deploy-production:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://signifly.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
